In [30]:
import numpy as np
import pandas as pd

In [31]:
# Question 1
pd.__version__

'3.0.5'

In [32]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'
!curl $data -o data.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  620k  100  620k    0     0  1336k      0 --:--:-- --:--:-- --:--:-- 1333k

In [33]:
df = pd.read_csv('data.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [34]:
# Question 2
df.index

RangeIndex(start=0, stop=10000, step=1)

In [35]:
# Question 3
df['fuel_type'].nunique()

3

In [36]:
# Question 4
(df.isnull().sum() > 0).sum()

np.int64(2)

In [37]:
# Question 5
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(2)

np.float64(41.2)

In [38]:
# Question 6
horsepower_col = df['horsepower']

In [39]:
initial_median_horsepower = horsepower_col.median()
initial_median_horsepower

np.float64(254.0)

In [40]:
most_frequent = horsepower_col.value_counts().idxmax()
most_frequent

np.float64(252.0)

In [41]:
after_fill_median = horsepower_col.fillna(most_frequent).median()

In [42]:
(initial_median_horsepower, after_fill_median)

(np.float64(254.0), np.float64(252.0))

In [43]:
initial_median_horsepower > after_fill_median

np.True_

In [44]:
# Question 7
asia_cars_df = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)
asia_cars_df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [45]:
X = asia_cars_df.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [46]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [47]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [48]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [49]:
w = (XTX_inv.dot(X.T)).dot(y)
w

array([0.13644777, 0.2327492 ])

In [50]:
sum(w)

np.float64(0.36919696904925203)