In [1]:
import pandas as pd
from narwhals.selectors import categorical

In [2]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv'

!curl $data -o data.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  272k  100  272k    0     0   485k      0 --:--:-- --:--:-- --:--:--  486k

In [63]:
df = pd.read_csv('data.csv')
df.head().T

,0,1,2,3,4
lead_source,organic_search,social_media,referral,paid_ads,referral
industry,technology,technology,retail,manufacturing,manufacturing
employment_status,employed,employed,employed,student,student
location,europe,south_america,europe,NaN,north_america
annual_income,88160.0,72688.0,44697.0,NaN,24062.0
number_of_courses_viewed,3,3,3,3,4
interaction_count,4,7,4,6,5
lead_score,0.64,0.72,0.58,0.57,0.62
converted,1,1,1,0,1

Data Preparation

In [64]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [65]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [82]:
categorical_cols = df.select_dtypes(include='str').columns.tolist()
numerical_cols = df.select_dtypes(exclude='str').columns.tolist()

In [83]:
categorical_cols, numerical_cols

(['lead_source', 'industry', 'employment_status', 'location'],
 ['annual_income',
  'number_of_courses_viewed',
  'interaction_count',
  'lead_score',
  'converted'])

In [84]:
df[categorical_cols] = df[categorical_cols].fillna('NA')
df[numerical_cols] = df[numerical_cols].fillna(0.0)

In [85]:
df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [86]:
from sklearn.model_selection import train_test_split

In [108]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=1
)

Question 1

In [88]:
from sklearn.metrics import roc_auc_score

In [89]:
y_val = df_test.converted.values

In [111]:
numerical_cols_without_converted = numerical_cols.copy()
numerical_cols_without_converted.remove('converted')
for numerical_col in numerical_cols_without_converted:
    auc = roc_auc_score(y_val, df_val[numerical_col])

    if auc < 0.5:
        auc = roc_auc_score(y_val, -df_val[numerical_col])


    print(numerical_col, round(auc, 3))

annual_income 0.613
number_of_courses_viewed 0.714
interaction_count 0.763
lead_score 0.783

Question 2

In [131]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression

In [138]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=1
)

In [139]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [140]:
numerical_cols_without_converted = numerical_cols.copy()
numerical_cols_without_converted.remove('converted')

In [141]:
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

In [142]:
del df_train['converted']
del df_val['converted']
del df_test['converted']

In [146]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical_cols + numerical_cols_without_converted].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [147]:
val_dict = df_val[categorical + numerical_cols_without_converted].to_dict(orient='records')
X_val = dv.transform(val_dict)

y_pred = model.predict_proba(X_val)[:, 1]

In [150]:
round(roc_auc_score(y_val, y_pred), 3)

0.732

Question 4

In [172]:
import numpy as np

thresholds = np.arange(0, 1.01, 0.01)
scores = []

for t in thresholds:
    actual_positive = (y_val == 1)
    actual_negative = (y_val == 0)

    predict_positive = (y_pred >= t)
    predict_negative = (y_pred < t)

    tp = (predict_positive & actual_positive).sum()
    tn = (predict_negative & actual_negative).sum()
    fp = (predict_positive & actual_negative).sum()
    fn = (predict_negative & actual_positive).sum()

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0
        else 0.0
    )
    scores.append((t, precision, recall, f1))

In [173]:
columns = ['threshold', 'precision', 'recall', 'f1']
df_scores = pd.DataFrame(scores, columns=columns)

In [174]:
df_scores

     threshold  precision    recall        f1
0         0.00      0.586  1.000000  0.738966
1         0.01      0.586  1.000000  0.738966
2         0.02      0.586  1.000000  0.738966
3         0.03      0.586  1.000000  0.738966
4         0.04      0.586  1.000000  0.738966
..         ...        ...       ...       ...
96        0.96      1.000  0.001706  0.003407
97        0.97      0.000  0.000000  0.000000
98        0.98      0.000  0.000000  0.000000
99        0.99      0.000  0.000000  0.000000
100       1.00      0.000  0.000000  0.000000

[101 rows x 4 columns]

In [175]:
df_scores.loc[df_scores['f1'].idxmax()]

threshold    0.410000
precision    0.619048
recall       0.976109
f1           0.757616
Name: 41, dtype: float64

Question 5

In [187]:
from sklearn.model_selection import KFold
from sklearn.feature_extraction import DictVectorizer

In [196]:
def train(df_train, y_train, C=1.0):
    dicts = df_train[categorical_cols + numerical_cols_without_converted].to_dict(orient='records')

    dv = DictVectorizer(sparse=False)
    X_train = dv.fit_transform(dicts)

    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000)
    model.fit(X_train, y_train)

    return dv, model

def predict(df, dv, model):
    dicts = df[categorical_cols + numerical_cols_without_converted].to_dict(orient='records')

    X = dv.transform(dicts)
    y_pred = model.predict_proba(X)[:, 1]

    return y_pred

In [197]:
scores = []
kfold = KFold(n_splits=5, shuffle=True, random_state=1)

for train_idx, val_idx in kfold.split(df_full_train):
    df_train = df_full_train.iloc[train_idx]
    df_val = df_full_train.iloc[val_idx]

    y_train = df_train.converted.values
    y_val = df_val.converted.values

    dv, model = train(df_train, y_train)
    y_pred = predict(df_val, dv, model)

    auc = roc_auc_score(y_val, y_pred)
    scores.append(auc)

In [201]:
round(np.mean(scores), 3), round(np.std(scores),3)

(np.float64(0.732), np.float64(0.007))

Question 6

In [203]:

kfold = KFold(n_splits=5, shuffle=True, random_state=1)

for C in [0.000001, 0.001, 1]:
    scores = []

    for train_idx, val_idx in kfold.split(df_full_train):
        df_train = df_full_train.iloc[train_idx]
        df_val = df_full_train.iloc[val_idx]

        y_train = df_train.converted.values
        y_val = df_val.converted.values

        dv, model = train(df_train, y_train, C=C)
        y_pred = predict(df_val, dv, model)

        auc = roc_auc_score(y_val, y_pred)
        scores.append(auc)

    print(f'C={C} {round(np.mean(scores), 3)} +- {round(np.std(scores), 3)}')

C=1e-06 0.617 +- 0.019
C=0.001 0.749 +- 0.01
C=1 0.732 +- 0.007